-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkK7swYBoJrBykPAi
ZMiZKLUEy1KYyjWdtLcvadfncu6gCgYIKoZIzj0DAQehRANCAASRjnbmz0dSqDPR
nW39lGDmurWVoKfmh0SBRTcXy2uA5G5a7Na/MfrnueoUzvhar3CjrCN4jmXOAyRD
0y1vuHQq
-----END PRIVATE KEY-----